import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'question.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.

@freezed
class Question with _$Question {
  const factory Question({
    required String question,
    required String correctAnswer,
    required List<String> incorrectAnswers,
  }) = _Question;

  factory Question.fromResponse(Map<String, Object?> json) => Question(
      question: json["question"] as String,
      correctAnswer: json["correct_answer"] as String,
      incorrectAnswers: (json["incorrect_answers"] as List<dynamic>)
          .map((e) => e.toString())
          .toList());
}
